# Generated by Django 3.2.3 on 2021-06-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_feedback_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mark',
            field=models.PositiveSmallIntegerField(max_length=1, verbose_name='Оценка'),
        ),
    ]
