# Generated by Django 3.2.3 on 2021-07-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210710_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='Другое', max_length=50, verbose_name='Категория'),
        ),
    ]
