# Generated by Django 3.2.3 on 2021-06-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mark',
            field=models.TextField(default=10, verbose_name='Оценка'),
            preserve_default=False,
        ),
    ]
