# Generated by Django 3.2.3 on 2021-06-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_feedback_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
